[package]
name = "enclone_help"
version = "0.2.6"
authors = ["""David Jaffe <david.jaffe@10xgenomics.com>,
              Wyatt McDonnell <wyatt.mcdonnell@10xgenomics.com>"""]
edition = "2018"
build = "build.rs"
publish = false

[dependencies]
ansi_escape = { git = "https://github.com/10XGenomics/rust-toolbox.git" }
enclone_core = { path = "../enclone_core" }
io_utils = "0.2.4"
string_utils = "0.1.1"
tables = { git = "https://github.com/10XGenomics/rust-toolbox.git" }

[build-dependencies]
chrono = "0.4.11"
prost-build = "0.5.0"
string_utils = "0.1.1"
