#!/bin/csh -e

# Build script for enclone.  The only thing missing from this is to run
# target/debug/build_html, however you should only need to do that rarely,
# and if you do need to, "cargo t" will catch the problem and should tell you
# what to do.
#
# add arg "plus" to get sha sum recomputation

# run rustfmt

cargo fmt --all

# compile rust code

cargo b

# build help pages

target/debug/enclone HTML STABLE_DOC      > pages/auto/help.main.html
target/debug/enclone HTML STABLE_DOC help > pages/auto/help.setup.html
foreach x (quick how command glossary example1 example2 support input input_tech parseable filter special lvars cvars amino display indels color faq developer all)
    target/debug/enclone help $x HTML STABLE_DOC > pages/auto/help.$x.html
end

# merge html pages

target/debug/merge_html

# update sha sum

if ( $1 == "plus" ) then
    find -L datasets -type f | sort | xargs cat | shasum -a256 > datasets_sha256
endif
