#!/bin/csh

# Copy website files to ~/public_html.  
#
# This wipes out a directory, so please read before using!

rm -rf ~/public_html/enclone

mkdir -p ~/public_html/enclone/src

cp -p index.html ~/public_html/enclone
cp -p README.md ~/public_html/enclone
cp -p LICENSE.txt ~/public_html/enclone
cp -p fonts/google_font_test.html ~/public_html/enclone
cp -pr {pages,fonts,img} ~/public_html/enclone
