#!/bin/csh

# Run .test over and over in an attempt to get it to fail.

set count = 1
while 1
    echo "TRY $count"
    ./test
    if ( $status != 0 ) then
        exit 1
    endif
    set count = `expr $count + 1`
end
