#!/bin/csh -e

# This is insanely fragile.

cargo update
cargo update -p time --precise 0.1.43
cargo update -p itertools:0.10.0 --precise 0.9.0
cargo update -p parking_lot_core:0.8.3 --precise 0.8.2
cargo update -p pprof --precise 0.4.2
cargo update -p ndarray:0.15.2 --precise 0.14.0
cargo update -p dirs --precise 3.0.1
