[package]
name = "enclone_build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["std", "clock"] }
itertools = "0.10"
pretty_trace = { git = "https://github.com/10XGenomics/enclone_ranger", branch = "macklin/merge-rust-toolbox", features = ["pprof"]}
string_utils = { git = "https://github.com/10XGenomics/enclone_ranger", branch = "macklin/merge-rust-toolbox" }
enclone_core = { git = "https://github.com/10XGenomics/enclone_ranger.git", branch = "main" }

[build-dependencies]
chrono = { version = "0.4", default-features = false, features = ["std", "clock"] }
string_utils = { git = "https://github.com/10XGenomics/enclone_ranger", branch = "macklin/merge-rust-toolbox" }
