name: build master
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: build-job
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/checkout
      - name: Install Rust
        run: |
          case $(rustc --version) in
            "rustc 1.40.0"*) ;;
            *) rustup default 1.40.0 ;;
          esac
          rustc --version
          rustfmt --version 
