name: Check formatting Ubuntu

on: 
  push:
    branches:
      - meryl/github-actions-1

jobs:
  build:
    # Job name is Greeting
    name: build-job-ubuntu
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        run: |
          case $(rustc --version) in
            "rustc 1.40.0"*) ;;
            *) rustup default 1.40.0 ;;
          esac
          rustc --version
          rustfmt --version 
      - name: Clone git repository
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/checkout
        uses: actions/checkout@master
      - name: Check Rust formatting
        run: cargo fmt -- --check
      - name: build-enclone
        run: cargo build --release --bin enclone && export PATH=target/release:$PATH
      - name: unit tests
        run: cargo test --release -- --nocapture
      - name: copy build
        run: |
          mkdir -p releases
          cp target/release/enclone enclone-ubuntu-1.0.0
          chmod 755 enclone-ubuntu-1.0.0
      - name: push build
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/releases/1234 \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --data '{
            "tag_name": "1.0.0",
            "target_commitish": "master",
            "name": "v1.0.0",
            "body": "Description of the release",
            "draft": false,
            "prerelease": false,
            }'
          curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --data-binary @enclone-ubuntu-1.0.0 \
          "https://uploads.github.com/repos/10XDev/enclone/releases/1234/assets?name=enclone-ubuntu-1.0.0"
