name: Test enclone linux

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: build-job-ubuntu
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout enclone master
        uses: actions/checkout@master
      - name: rustup targets
        run: rustup show
      - name: Check Rust formatting
      # Check formatting
        run: cargo fmt -- --check
      - name: build-enclone
        run: cargo build --release
      - name: unit tests
        run: cargo test --release --features basic -- --nocapture
