name: Check formatting Ubuntu

on: pull_request

jobs:
  build:
    # Job name is Greeting
    name: build-job-ubuntu
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        run: |
          case $(rustc --version) in
            "rustc 1.40.0"*) ;;
            *) rustup default 1.40.0 ;;
          esac
          rustc --version
          rustfmt --version 
      - name: Clone git repository
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/checkout
        uses: actions/checkout@master
      - name: Check Rust formatting
        run: cargo fmt -- --check
      - name: build-enclone
        run: cargo build --release --bin enclone && export PATH=target/release:$PATH
      - name: unit tests
        run: cargo test --release -- --nocapture
      - name: copy build
        run: |
          mkdir -p releases
          cp target/release/enclone releases/enclone-ubuntu-1.0.0
      - name: push build
        run: |
          git config --global credential.helper store
          git config --global user.name 'github action'
          echo ${GITHUB_REPOSITORY} 
          git add releases/enclone-ubuntu-1.0.0
          git commit -m "Update enclone-ubuntu-1.0.0"
          git pull --rebase origin HEAD:master
          git push --rebase origin HEAD:master
