name: Test enclone MacOS

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: build-job-macos
    # This job runs on MacOS Catalina
    runs-on: macos-latest
    steps:
      - name: rust version
        run: rustup default 1.43.0
      - name: Checkout enclone master
        uses: actions/checkout@master
      - name: add rustfmt 
        run: rustup component add rustfmt --toolchain 1.43.0-x86_64-apple-darwin
      - name: Check Rust formatting
      # Check formatting
        run: cargo fmt -- --check
      - name: build-enclone
        run: cargo build --release
      - name: unit tests
        run: cargo test --release --features basic -- --nocapture 
