name: Check formatting Ubuntu
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - meryl/github-actions-1

jobs:
  build:
    # Job name is Greeting
    name: build-job-ubuntu
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        run: |
          case $(rustc --version) in
            "rustc 1.40.0"*) ;;
            *) rustup default 1.40.0 ;;
          esac
          rustc --version
          rustfmt --version 
      - name: Checkout git repository
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/checkout
      - uses: actions/checkout@meryl/github-actions-1
      - name: Check Rust formatting
        run: cargo fmt -- --check
      - name: build-enclone
        run: cargo build --release --bin enclone && export PATH=target/release:$PATH
      - name: unit tests
        run: cargo test --release -- --nocapture
      - name: copy build
        run: cp target/release/enclone enclone-ubuntu-1.0.0
      - name: push build
        run: |
          echo 'https://10xbuild:${{secrets.GITHUB_PAT}}@github.com' >~/.git-credentials
          git config --global credential.helper store
          git config --global user.name 'github action'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add enclone-ubuntu-1.0.0
          git commit -m "Update enclone-ubuntu-1.0.0"
          git push
