name: Test enclone MacOS

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: build-job-macos
    # This job runs on MacOS Catalina
    runs-on: macos-latest
    steps:
      - name: Checkout enclone master
        uses: actions/checkout@master
      - name: rustup check
        run: |
          rustup -V
          rustup component add rustfmt --toolchain stable-x86_64-apple-darwin
          rustup -V
      - name: Check Rust formatting
      # Check formatting
        run: cargo fmt -- --check
      - name: build-enclone
        run: cargo build --release
      - name: unit tests
        run: cargo test --release --features basic -- --nocapture 
