name: Test enclone MacOS

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: build-job-macos
    # This job runs on MacOS Catalina
    runs-on: macos-latest
    steps:
      - name: Checkout enclone master
        uses: actions/checkout@master
      - name: rustup-version
        run: rustup -V
      - name: rustup reinstall
        run: rustup toolchain remove stable && rustup toolchain install stable
      - name: rustup-version
        run: rustup -V
      - name: Check Rust formatting
      # Check formatting
        run: cargo fmt -- --check
      - name: build-enclone
        run: cargo build --release
      - name: unit tests
        run: cargo test --release --features basic -- --nocapture 
