name: Test enclone linux

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: build-job-ubuntu
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: rust version
        run: rustup default 1.42.0
      - name: Checkout enclone master
        uses: actions/checkout@master
      - name: add rustfmt
        run: rustup component add rustfmt --toolchain 1.42.0-x86_64-unknown-linux-gnu
      - name: Check Rust formatting
      # Check formatting
        run: cargo fmt -- --check
      - name: build-enclone
        run: cargo build --release
      - name: unit tests
        run: cargo test --release --features basic -- --nocapture
